Pin jsdom to 15.2.1
If we're lucky this fixes this error:
```
/home/travis/build/fthomas/kartograffel/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/fthomas/kartograffel/node_modules/jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)
```